interface Env {
  DETA_PROJECT_KEY: string;
  DETA_PROJECT_ID: string;
  TWITCH_CLIENT_ID: string;
  TWITCH_CLIENT_SECRET: string;
	TWITCH_ACCESS_TOKEN: string;
	TWITCH_REFRESH_TOKEN: string;
  PORT: string;
}

export const env: Env = {
	DETA_PROJECT_KEY: process.env.DETA_PROJECT_KEY!,
	DETA_PROJECT_ID: process.env.DETA_PROJECT_ID!,
	TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID!,
	TWITCH_CLIENT_SECRET: process.env.TWITCH_CLIENT_SECRET!,
	TWITCH_ACCESS_TOKEN: process.env.TWITCH_ACCESS_TOKEN!,
	TWITCH_REFRESH_TOKEN: process.env.TWITCH_REFRESH_TOKEN!,
	PORT: process.env.PORT!,
}